### ISSUE TITLE
Glitch: unnecessary(?) height constraint on .nav-buttons-container sometimes causes item overlap

### ISSUE THREAD

**Issue by 229c9cf0** [davidgolding/obsidian-big-sur-aesthetic#4]
Currently, the height of `.nav-buttons-container` is restricted to `28px`. Some plugins put bigger elements in there, causing the contents to overflow and appear under the stuff that follows after. (I.e. several elements appear on top of each other.) I deleted that line to get rid of that problem, and it seems that didn't cause any other changes apart from fixing the layout. So maybe that line can just go away?

```
    174
    175 .nav-buttons-container {
--- 176     height: 28px;
    177     padding: 0px 1px 0px 0px;
    178     justify-content: flex-end;
    179 }
    180
```

**Comment by davidgolding** [comment]
Fixed in cb168f88b7c220edf0a6d2195ef6d3fe3dd26d3f
